- CODE_OF_CONDUCT.md
From Contributor Covenant Code of Conduct
> Creation of Code of Conduct

- scripts/devinstall.py
Hacía falta un '\' en la ruta para encontrar coverage, así como su configuración para windows.  #3
> Solución al issue #3 relacionado con rutas de binarios

- construbot/core/context.py
- construbot/core/menu.py
- construbot/static/css/project.css
- construbot/templates/menu.html
- construbot/templates/pages/about.html
- construbot/users/views.py
Se hace modificación en menu.py mostrando estructura tentativa para el menú que verá el usuario, así como modificación del método para hacer reverse a las url's, se agregó un nivel más de profundidad, así como en la página "About Us" incrusté algunas pruebas para diseño de tabla y listado de documentos.
> Reestructura de menú

- construbot/proyectos/forms.py
- construbot/proyectos/views.py
- construbot/static/css/project.css
- construbot/static/js/project.js
- construbot/templates/base.html
- construbot/templates/proyectos/contrato_form.html
- construbot/templates/proyectos/listado_de_contratos.html
Se añade el datepicker, con los requisitos previos (formato en AAAA MM DD), sólo que hay un problema al ejecutar el POST, sólo regresa de vuelta al formulario sin renderizar errores.
> adicion de datepicker

- construbot/proyectos/forms.py
- construbot/proyectos/views.py
Se pasa "currently_at" como get_initial para el formulario de contrato.
> Se pasa "currently_at" como get_initial

- construbot/core/menu.py
- construbot/proyectos/forms.py
- construbot/proyectos/models.py
- construbot/proyectos/urls.py
- construbot/proyectos/views.py
- construbot/static/css/project.css
- construbot/templates/menu.html
- construbot/templates/proyectos/cliente_list.html
- construbot/templates/proyectos/contrato_list.html
- construbot/templates/proyectos/detalle_de_cliente.html
- construbot/templates/proyectos/detalle_de_sitio.html
- construbot/templates/proyectos/sitio_list.html
Corrección del menú, las clases y estilos están ajustados como deberían.
> Consolidacion de Sitios y Clientes

- construbot/static/css/project.css
- construbot/templates/base.html
- construbot/templates/proyectos/cliente_list.html
- construbot/templates/proyectos/contrato_list.html
- construbot/templates/proyectos/detalle_de_cliente.html
- construbot/templates/proyectos/detalle_de_contrato.html
- construbot/templates/proyectos/detalle_de_sitio.html
- construbot/templates/proyectos/sitio_list.html
Se adicionan nuevos estilos, idénticos a la versión que actualmente está en producción. Sólo faltan hovers y formularios por AJAX.
> nuevos estilos

- construbot/proyectos/views.py
- construbot/static/js/project.js
modificacion de peticion AJAX y modificación del query para detalle de contrato.
> modificacion de peticion AJAX

- construbot/proyectos/forms.py
- construbot/proyectos/models.py
- construbot/proyectos/urls.py
- construbot/proyectos/views.py
- construbot/static/css/project.css
- construbot/static/js/project.js
- construbot/templates/menu.html
- construbot/templates/proyectos/catalogo-conceptos-inline.html
- construbot/templates/proyectos/cliente_list.html
- construbot/templates/proyectos/concept_list.html
- construbot/templates/proyectos/contrato_list.html
- construbot/templates/proyectos/creation_form.html
- construbot/templates/proyectos/detalle_de_cliente.html
- construbot/templates/proyectos/detalle_de_contrato.html
- construbot/templates/proyectos/detalle_de_sitio.html
- construbot/templates/proyectos/sitio_list.html
Es necesario hacer vista de detalle y listado de Diccionario.
> Adicion de formularios para ediciones, y la creacion de Destinatario

- construbot/proyectos/models.py
- construbot/proyectos/tests.py
- construbot/proyectos/urls.py
- construbot/proyectos/views.py
- construbot/static/js/project.js
- construbot/templates/proyectos/destinatario_list.html
- construbot/templates/proyectos/detalle_de_destinatario.html
También de la vista para detalle y listado.
> termino de formularios para destinatario

- construbot/proyectos/factories.py
- construbot/proyectos/models.py
- construbot/proyectos/tests.py
- construbot/proyectos/urls.py
- construbot/proyectos/views.py
- construbot/static/js/project.js
- construbot/templates/proyectos/destinatario_list.html
- construbot/templates/proyectos/detalle_de_destinatario.html
Es necesario modificar el modelo de Destinatario, 2 pruebas fallan, es necesario modificar la obtención de los objetos para que el 404 sea levantado debidamente.
> adicion de factory para Destinatario, tests cubiertos para vistas de Listado y Detalle en Proyectos

- construbot/proyectos/tests.py
Completado para la vista de inline concept.
> Avance con tests

- construbot/proyectos/tests.py
- construbot/proyectos/views.py
Faltan tests para probar si el objeto se guardó en base de datos.
> Avance con tests para autocompletados

- construbot/proyectos/tests.py
- construbot/proyectos/views.py
Son para SitioEditView y DestinatarioEditView.
> avance con pruebas lógicas

- construbot/proyectos/factories.py
- construbot/proyectos/forms.py
- construbot/proyectos/management/commands/poblar.py
- construbot/proyectos/tests.py
- construbot/proyectos/views.py
- construbot/static/js/project.js
- construbot/templates/proyectos/contrato_detail.html
Actualizado hasta el punto de usar el comando "Python manage.py poblar".
> Rebase de todos los commits.

- construbot/proyectos/models.py
- construbot/proyectos/views.py
- construbot/static/css/project.css
- construbot/static/js/project.js
- construbot/templates/proyectos/contrato_detail.html
- construbot/templates/proyectos/contrato_list.html
- construbot/templates/proyectos/estimate_detail.html
Corrección de estilos para formulario responsivo.
Adición de botón de impresión.
Etiqueta {% lorem %}
> Termino de la vista de detalle de estimación.

- construbot/proyectos/forms.py
- construbot/static/css/project.css
- construbot/static/js/project.js
- construbot/templates/proyectos/estimate_detail.html
- construbot/templates/proyectos/estimate_form.html
- construbot/templates/proyectos/file_input.html
Detalles estéticos y funcionales para subida de imagenes.
> correccion de detalles para la vista de formulario de estimacion

- construbot/proyectos/management/commands/poblar.py
- construbot/static/css/project.css
- construbot/templates/base.html
- construbot/users/forms.py
- construbot/users/tests/test_adapters.py
- construbot/users/tests/test_models.py
- construbot/users/tests/test_urls.py
- construbot/users/tests/test_views.py
- construbot/users/urls.py
- construbot/users/views.py
Reestructura del menu y barra de navegacion.
> resolucion de conflictos con la poblacion de base de datos.

- construbot/proyectos/tests/test_templates.py
- construbot/proyectos/tests/test_urls.py
- construbot/proyectos/urls.py
- construbot/proyectos/views.py
- construbot/templates/base.html
- construbot/templates/proyectos/catalogo-conceptos-inline.html
- construbot/templates/proyectos/creation_form.html
- construbot/templates/proyectos/estimate_detail.html
- construbot/templates/proyectos/estimate_form.html
los test fueron para URL's y templates de proyectos
> reestructura de urls, se agregan nuevos test.

- construbot/proyectos/forms.py
- construbot/proyectos/urls.py
- construbot/proyectos/views.py
- construbot/static/css/project.css
- construbot/static/js/project.js
- construbot/templates/base.html
- construbot/templates/proyectos/concept_estimate.html
- construbot/templates/proyectos/concept_generator.html
- construbot/templates/proyectos/estimate_detail.html
- Parte de conceptos en detalle de contrato.
- Menu abatible cuando la resolucion es menor a 600px.
- Separación de templates de conceptos.
- Autocompletado de User.
> adicion de detalles esteticos

- construbot/static/js/project.js
- construbot/templates/proyectos/creation_form.html
No se permite la edicion de sitio hasta haber llenado cliente.
> correccion de bug en formulario

- construbot/core/menu.py
- construbot/functional_tests/test_proyectos_views.py
- construbot/functional_tests/test_user_views.py
- construbot/users/views.py
Se adaptan a cambios menores de diseño y funcionalidad.
> modificación de pruebas funcionales

- construbot/functional_tests/test_proyectos_views.py
- construbot/functional_tests/test_user_views.py
- construbot/users/urls.py
Se arregla una URL para ser compatible con todos los username.
> detalles menores

- construbot/proyectos/forms.py
- construbot/proyectos/models.py
- construbot/static/css/project.css
- construbot/templates/proyectos/contrato_detail.html
- construbot/templates/proyectos/index.html
- construbot/templates/users/user_list.html
Queda una migración pendiente, no se aplicó, consultar. Se trata de la longitud máxima para un concepto.
> se resuelven detalles estéticos

- construbot/proyectos/utils.py
- construbot/proyectos/views.py
:+1: :mexico: Viva México :mexico: :+1:
> Se crean Retenciones con archivos de Excel

- construbot/static/css/project.css
- construbot/static/js/project.js
- construbot/templates/proyectos/contrato_detail.html
- construbot/templates/proyectos/contrato_list.html
- construbot/templates/proyectos/reporte_estimaciones_subcontratos.html
> Se resuleve #186

- construbot/static/js/project.js
- construbot/templates/proyectos/reporte_estimaciones_subcontratos.html
> avance con la vista de reporte de estimaciones

- construbot/static/js/project.js
> Se cambia JS para reporte de Subestimación, La 3ra es la vencida.
